// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewPeerProfile(arg1, arg2) {
  return window['go']['main']['App']['AddNewPeerProfile'](arg1, arg2);
}

export function CreateNewPost(arg1) {
  return window['go']['main']['App']['CreateNewPost'](arg1);
}

export function GetMyPublickey() {
  return window['go']['main']['App']['GetMyPublickey']();
}

export function IsServer() {
  return window['go']['main']['App']['IsServer']();
}

export function JoinGossipNet(arg1) {
  return window['go']['main']['App']['JoinGossipNet'](arg1);
}

export function ViewAllPosts() {
  return window['go']['main']['App']['ViewAllPosts']();
}

export function ViewAllProfiles() {
  return window['go']['main']['App']['ViewAllProfiles']();
}

export function ViewOneProfile(arg1) {
  return window['go']['main']['App']['ViewOneProfile'](arg1);
}
