// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dba} from '../models';

export function AddNewPeerProfile(arg1:string,arg2:string):Promise<void>;

export function CreateNewPost(arg1:string):Promise<void>;

export function GetMyPublickey():Promise<string>;

export function IsServer():Promise<boolean>;

export function JoinGossipNet(arg1:string):Promise<void>;

export function ViewAllPosts():Promise<Array<dba.Post>>;

export function ViewAllProfiles():Promise<Array<dba.Peer>>;

export function ViewOneProfile(arg1:string):Promise<dba.Peer>;
